[package]
name = "swactor-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "0.4", features = ["arbitrary-derive"] }
arbitrary = { version = "1", features = ["derive"] }
swactor = { path = "..", default-features = true }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "fuzz_runtime"
path = "fuzz_targets/fuzz_runtime.rs"
doc = false

[[bin]]
name = "fuzz_mt"
path = "fuzz_targets/fuzz_mt.rs"
doc = false
