[package]
name = "swactor-process-context"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"
publish = false

[dependencies]
swactor = { path = "../..", features = ["serde"] }
swactor-process = { path = "../process" }
swactor-engine = { path = "../engine" }
data-plane = { path = "../data-plane" }
serde = { version = "1", features = ["derive"] }
telemetry = { path = "../telemetry" }
libc = "0.2"

[dev-dependencies]
proptest = "1"

[lints]
workspace = true
