[package]
name = "node"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "swactor-node"
path = "src/main.rs"

[dependencies]
swactor = { path = "../..", features = ["serde", "tracing", "transport"] }
distribution = { path = "../distribution" }
runtime-dashboard = { path = "../runtime-dashboard", features = ["distribution"] }
clap = { version = "4", features = ["derive"] }
ctrlc = "3"
