[build-system]
requires = ["maturin>=1.7,<2"]
build-backend = "maturin"

[project]
name = "swactor"
version = "0.1.0"
requires-python = ">=3.9"

[dependency-groups]
dev = ["jupyter", "ipykernel", "pytest"]

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "Cargo.toml" },
    { file = "src/**/*.rs" },
    { file = "../../Cargo.toml" },
    { file = "../../src/**/*.rs" },
]
