[package]
name = "swactor-process"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"

[dependencies]
swactor = { path = "../..", default-features = false, features = ["no_random"] }
telemetry = { path = "../telemetry" }
crossbeam-queue = "0.3.12"
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
