[package]
name = "data-plane"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"
publish = false

[dependencies]
telemetry = { path = "../telemetry" }
serde = { version = "1", features = ["derive"] }
swactor = { path = "../.." }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
